# Generated by Django 3.2.7 on 2022-05-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel',
            name='excel_file_upload',
            field=models.ImageField(default=0, upload_to='excel'),
        ),
    ]
