# Generated by Django 3.2.7 on 2022-05-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_excel_excel_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='excel_file_upload',
            field=models.FileField(default=0, upload_to='excel'),
        ),
    ]
