# Generated by Django 3.2.7 on 2022-05-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_excel_excel_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='excel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
