# Generated by Django 3.2.7 on 2022-05-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220520_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
