# Generated by Django 3.2.7 on 2022-05-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_excel_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='beforefetch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniquename', models.CharField(max_length=100)),
                ('excel_file_upload', models.FileField(upload_to='before_fetch')),
                ('template_file_upload', models.FileField(upload_to='before_fetch')),
            ],
        ),
    ]
