# Generated by Django 3.2.7 on 2022-05-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_statusdetails_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusdetails',
            name='statusnamecheck',
            field=models.CharField(default=0, max_length=10000),
        ),
    ]
