# Generated by Django 3.2.7 on 2022-05-23 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_statusdetails_statusnamecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusdetails',
            name='dateadded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
